#ifndef CUSTOM_VARS_H
#define CUSTOM_VARS_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

// Custom variable functions (not auto-generated by EEZ)
extern const char *get_var_odometer();
extern void set_var_odometer(const char *value);
extern const char *get_var_speed();
extern void set_var_speed(const char *value);
extern const char *get_var_fps();
extern void set_var_fps(const char *value);
extern const char *get_var_rpm();      // ADD THIS
extern void set_var_rpm(const char *value);  // ADD THIS

#ifdef __cplusplus
}

// C++ only
void update_odometer_display(float odometer_km);
void update_speed_display(float speed_kmh);
void update_fps_display(uint32_t fps);
void update_rpm_display(uint32_t rpm);  // ADD THIS

#endif

#endif
